"""Builds hooks/dogart.js: the rottweiler as chunky pixel art at each sprite size.

Source: art/rottweiler.png, a generated illustration with its background removed.
Run `python art/build_dog.py` after replacing the image or changing a size.

The art is deliberately low-res and flat: few pixels, a small palette, posterized
shading. A size can be built at half resolution and drawn with `scale` 2, so each
art pixel is a 2x2 block on screen.

Each grid uses its own palette keys (Latin-1 letters, so they never clash with
sprite.js's), plus two reserved keys sprite.js draws itself:
  RIM  the one-pixel outline (recolored by level)
  EYE  the eye (drawn open, blinking or closed by state)
"""
import json, os
from PIL import Image, ImageEnhance

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, 'rottweiler.png')
OUT = os.path.join(HERE, '..', 'hooks', 'dogart.js')

KEYS = [chr(c) for c in range(0xC0, 0x100) if chr(c) not in '×÷']
RIM, EYE = '¤', '¢'
# name: (art pixels wide, on-screen scale)
SIZES = {'full': (21, 2), 'mini': (22, 1)}
COLORS = 8
assert len(KEYS) >= len(SIZES) * COLORS


def flat(r, g, b):
    """Snap a palette color to the cartoon set: near-grays become charcoal with a
    hint of blue, and anything green (the source's goggle glow) becomes coat."""
    if g > r + 25 and g > b + 15:
        return 46, 46, 56
    if max(r, g, b) - min(r, g, b) > 45:
        return r, g, b
    lum = round(0.3 * r + 0.55 * g + 0.15 * b)
    return max(0, lum - 2), max(0, lum - 1), min(255, lum + 6)


def build(width, offset):
    src = Image.open(SRC).convert('RGBA')
    src = src.crop(src.getbbox())
    h = round(src.height * width / src.width)
    rgb = src.convert('RGB')
    alpha = src.split()[3]

    # The eye: the source's glowing pixels sit where the eye is
    eye_src = Image.new('L', src.size, 0)
    ep, sp = eye_src.load(), rgb.load()
    for y in range(src.height):
        for x in range(src.width):
            r, g, b = sp[x, y]
            if g > 170 and r < 140 and g - r > 70:
                ep[x, y] = 255

    # Lift blacks so the coat reads as charcoal, punch the contrast, posterize
    rgb = rgb.point(lambda c: c if c >= 90 else round(30 + 60 * c / 90))
    rgb = ImageEnhance.Contrast(rgb).enhance(1.3)
    rgb = ImageEnhance.Color(rgb).enhance(1.2)
    small = rgb.resize((width, h), Image.BOX)
    a = list(alpha.resize((width, h), Image.BOX).getdata())
    eye = list(eye_src.resize((width, h), Image.BOX).getdata())

    q = small.quantize(colors=COLORS, method=Image.Quantize.MAXCOVERAGE, dither=Image.Dither.NONE)
    pal = q.getpalette()[: COLORS * 3]
    idx = list(q.getdata())

    on = [[a[y * width + x] > 110 for x in range(width)] for y in range(h)]
    # One eye cell at most per row, and only the brightest spots
    rows = []
    for y in range(h):
        row = ''
        for x in range(width):
            i = y * width + x
            if not on[y][x]:
                row += '.'
            elif eye[i] > 90:
                row += EYE
            elif (y == 0 or not on[y - 1][x]) or (x == 0 or not on[y][x - 1]) or (x == width - 1 or not on[y][x + 1]):
                row += RIM
            else:
                row += KEYS[offset + idx[i]]
        rows.append(row)
    palette = {KEYS[offset + i]: '%02x%02x%02x' % flat(*pal[i * 3: i * 3 + 3]) for i in range(COLORS)}
    return {'width': width, 'height': h, 'rows': rows, 'palette': palette}


def main():
    # Each size gets its own key range so both palettes can share one lookup
    out = {}
    for i, (name, (width, scale)) in enumerate(SIZES.items()):
        out[name] = build(width, i * COLORS)
        out[name]['scale'] = scale
    body = json.dumps(out, ensure_ascii=False, indent=1)
    with open(OUT, 'w', encoding='utf-8') as f:
        f.write('// Generated by art/build_dog.py from art/rottweiler.png. Do not edit by hand.\n')
        f.write("export const RIM = '%s'\nexport const EYE = '%s'\n" % (RIM, EYE))
        f.write('export const DOG = ' + body + '\n')
    for name, s in out.items():
        print(name, s['width'], 'x', s['height'], 'x', s['scale'])


if __name__ == '__main__':
    main()
